### PR TITLE
Fix spaces in GitHub discussion code

### LINKED ISSUE #63: Code sections in the discussion viewer are not `white-space: pre-wrap`
_If you've been granted access – before submission, double-check for any sensitive or
confidential info from RFDs._

GitHub comments on lines of an RFD that contain multiple spaces (e.g. box drawings) aren't rendered correctly in the discussion viewer on the site.

See the comment at https://github.com/oxidecomputer/rfd/pull/765#discussion_r1667071460 and its corresponding entry when you click the comments button on the RFD site for an example.

### PR DESCRIPTION
**Pull request by benjaminleonard**
Fixes #63

### CODE REVIEW

**Review by iliana — APPROVED** [review]
I don't think I have any way to test this since the Vercel preview doesn't support Google auth, but I imagine this is correct!

**Comment by benjaminleonard** [comment]
Likewise I borked my local env vars to test GitHub discussions.

...fix env vars
...merge and hope for the best

**Comment by iliana** [comment]
We'll all find out together!

**Comment by benjaminleonard** [comment]
#360noscope

**Pull request merged**
